# This is the build specification for building java based lambda.
# First step in the process is to run the test and then perform package and upload the package to S3
version: 0.2
phases:
  install:
    commands:
      - export HOME_DIR=$PWD
      - cd lambda/others/sns-slack
      - npm install -g request
  build:
    commands:
      - echo Build started on `date`
      - zip -9rq code.zip .
  post_build:
    commands:
      - echo Build completed on `date`
      - cd $HOME_DIR
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambda-deployment-code --output-template-file projectw-cfn-template.yaml
artifacts:
  types: zip
  files:
    - projectw-cfn-template.yaml
    - projectw-cfn-parameter.json

