# This is the build specification for building java based lambda.
# First step in the process is to run the test and then perform package and upload the package to S3
version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - export BUILD_DIR=$PWD
      - export BUILD_ID=`echo $CODEBUILD_BUILD_ID | sed -e 's/:/\n/g' | awk 'NR==2'`
      - cd ByeWorldLambda && mvn test
      - cd ../HelloWorldLambda && mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - cd ../ByeWorldLambda && mvn package && cd ..
      - aws cloudformation package --template-file samTemplate_java.yaml --s3-bucket lambda-deployment-code --output-template-file projectw-cfn-template-java.yaml
      ## Collect the code coverage reports and upload to s3
      - cd $BUILD_DIR/ByeWorldLambda/target/site/jacoco-ut
      - zip -9rq bye_report.zip .
      - aws s3 cp bye_report.zip s3://projectw-code-coverage-reports/bye/$BUILD_ID/ByeWordLambda.zip
      - cd $BUILD_DIR/HelloWorldLambda/target/site/jacoco-ut
      - zip -9rq hello_report.zip .
      - aws s3 cp hello_report.zip s3://projectw-code-coverage-reports/hello/$BUILD_ID/HelloWorldLambda.zip
artifacts:
  types: zip
  files:
    - projectw-cfn-template-java.yaml
    - projectw-cfn-parameter.json
    - projectw-cfn-parameter-qa.json
    - copy_artifacts.py
