version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - cd ByeWorldLambda && mvn test
      - cd ../HelloWorldLambda && mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - cd ../ByeWorldLambda && mvn package && cd ..
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket lambda-deployment-code --output-template-file projectw-cfn-template.yaml
artifacts:
  types: zip
  files:
    - projectw-cfn-template.yaml

