# This is the build specification for building java based lambda.
# First step in the process is to run the test and then perform package and upload the package to S3
version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - cd ByeWorldLambda && mvn test
      - cd ../HelloWorldLambda && mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - cd ../ByeWorldLambda && mvn package && cd ..
      - aws cloudformation package --template-file samTemplate_java.yaml --s3-bucket lambda-deployment-code --output-template-file projectw-cfn-template-java.yaml
artifacts:
  types: zip
  files:
    - projectw-cfn-template-java.yaml
    - projectw-cfn-parameter.json

