AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This is the function to get Position details given a position id from SW SOAP APIs
Parameters: 
  ApiUsername:
    Type: String
    Description: This is the ShiftWise Endpoint Username that will be used when invoking SW APIs. This must be encrypted using KMS key
  ApiPassword:
    Type: String
    Description: This is the ShiftWise Endpoint password that will be used when invoking SW APIs. This must be encrypted using KMS key
  ShiftWiseURL:
    Type: String
    Description: This is the ShiftWise Endpoint URL that will be used to invoke SOAP APIs
  SlackChannel:
    Type: String
    Description: Slack channel for notifications
  SlackWebhookUrl:
    Type: String
    Description: Slack webhook
Resources:
  GetPositionDetails:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.lambda.hello.LambdaFunctionHandler::handleRequest
      Runtime: java8
      CodeUri: ./HelloWorldLambda/target/hello-1.0.0.jar
      Role: arn:aws:iam::706469024316:role/lambda_custom_role
      Environment:
        Variables:
          API_USERNAME: !Ref ApiUsername
          API_PASSWORD: !Ref ApiPassword
          SW_API_URL: !Ref ShiftWiseURL
  ShiftwiseNotification:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.lambda.bye.LambdaFunctionHandler::handleRequest
      Runtime: java8
      CodeUri: ./ByeWorldLambda/target/bye-1.0.0.jar
      Role: arn:aws:iam::706469024316:role/lambda_custom_role
      Environment:
        Variables:
          API_USERNAME: !Ref ApiUsername
          API_PASSWORD: !Ref ApiPassword
          SW_API_URL: !Ref ShiftWiseURL
      Events:
        HttpPost:
          Type: Api
          Properties:
            Path: OnboardLogin/login
            Method: post