AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: This is the function to get Position details given a position id from SW SOAP APIs
Resources:
  GetPositionDetails:
    Type: AWS::Serverless::Function
    Properties:
    Handler: com.amazonaws.lambda.hello.LambdaFunctionHandler::handleRequest
    Runtime: java8
    CodeUri: ./HelloWorldLambda/target/hello-1.0.0.jar
    Environment:
      API_USERNAME: !Sub '${API_USERNAME}'
      API_PASSWORD: !Sub '${API_PASSWORD}'
      SW_API_URL: !Sub '${SHIFTWISE_API_URL}'
  ShiftwiseNotification:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.amazonaws.lambda.bye.LambdaFunctionHandler::handleRequest
      Runtime: java8
      CodeUri: ./ByeWorldLambda/target/bye-1.0.0.jar
      Environment:
        API_USERNAME: !Sub '${API_USERNAME}'
        API_PASSWORD: !Sub '${API_PASSWORD}'
        SW_API_URL: !Sub '${SHIFTWISE_API_URL}'
